### PR TITLE
Classify all items as +1 or -1.

### PR DESCRIPTION
**Pull request by alexfernandez**
I took a shot at my own issue, https://github.com/kitze/awesome-conference-practices/issues/5. I hope I did not break anything! Will require redoing all other PRs, sorry for that.

### CODE REVIEW

**Comment by kitze** [comment]
Uh, I'm really not sure about this one ... there must be a better way to do it

**Comment by alexfernandez** [comment]
Cool, all yours then 😁

**Comment by JamesMilnerUK** [comment]
Maybe sub sectioning to "Dos" and "Dont's" ?

**Comment by erikras** [comment]
What about a TOC that had a dos and don'ts dichotomy that anchor-linked to each item?

Might be hard to maintain....

**Comment by erikras** [comment]
Every time I see a document like this, I immediately think of different useful ways to "query" the data into separate lists. 🤦‍♂️

**Comment by kitze** [comment]
Sorry but closing this one until we find a better way to structure the doc. It's fine for now.

**Pull request closed without merging**
